ar_model:
  target: RandAR.model.randar_gpt.RandARTransformer
  params:
    n_layer: 8      
    n_head: 8         
    dim: 256          
    model_type: c2i
    vocab_size: 35173 
    block_size: 256    
    num_classes: 1    # Single dummy class for now
    cls_token_num: 1
    resid_dropout_p: 0.1
    ffn_dropout_p: 0.1
    drop_path_rate: 0.0
    token_dropout_p: 0.0
    position_order: random
    grad_checkpointing: False
    zero_class_qk: True
    num_inference_steps: 32  

dataset:
  target: RandAR.dataset.nlcd_dataset.NLCDDataset
  params:
    data_path: "data/data_size32_ratio8.npz"
    split: train
    max_samples: 1000000
tokenizer:
  target: RandAR.model.nlcd_tokenizer.NLCDTokenizer
  params:
    vocab_size: 35173

accelerator:
  gradient_accumulation_steps: 1
  mixed_precision: "no"
  log_with: wandb

optimizer:
  lr: 0.0005
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  max_grad_norm: 1.0
  skip_grad_iter: 0
  skip_grad_norm: 1000

lr_scheduler:
  type: cosine
  warm_up_iters: 500
  min_lr_ratio: 0.1
  num_cycles: 0.5

# training related parameters
exp_name: "randar_nlcd_64_tokenized"
max_iters: 100000  
global_batch_size: 32
ema: False
ema_decay: 0.9999

num_workers: 4
log_every: 100
ckpt_every: 5000
visualize_every: 1000
keep_last_k: 2
resume_from: "results/randar_nlcd_64_tokenized/checkpoints/iter_18000"
global_seed: 42

results_dir: "results/" 
gpt_ckpt: None

# for eval fid:
vq_ckpt: None  # Not needed

# for wandb
wandb_entity: "ckrapu"
wandb_offline: False  # Run offline for testing 