ar_model:
  target: RandAR.model.randar_gpt.RandARTransformer
  params:
    n_layer: 8        # Increased from 4 for more complex data
    n_head: 8         # Increased from 4
    dim: 256          # Increased from 128
    model_type: c2i
    vocab_size: 27626    # 16 unique NLCD values
    block_size: 16    # 8x8 image
    num_classes: 1    # Single dummy class for now
    cls_token_num: 1
    resid_dropout_p: 0.1
    ffn_dropout_p: 0.1
    drop_path_rate: 0.0
    token_dropout_p: 0.0
    position_order: random
    grad_checkpointing: False
    zero_class_qk: True
    num_inference_steps: 32  # For parallel decoding

dataset:
  target: RandAR.dataset.nlcd_dataset.NLCDDataset
  params:
    data_path: "data/data_size8_ratio8.npz"
    split: train
    max_samples: 1000000
tokenizer:
  target: RandAR.model.nlcd_tokenizer.NLCDTokenizer
  params:
    vocab_size: 5807

accelerator:
  gradient_accumulation_steps: 1
  mixed_precision: "no"
  log_with: wandb

optimizer:
  lr: 0.001  # Slightly lower than toy example
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  max_grad_norm: 1.0
  skip_grad_iter: 0
  skip_grad_norm: 1000

lr_scheduler:
  type: cosine
  warm_up_iters: 500
  min_lr_ratio: 0.1
  num_cycles: 0.5

# training related parameters
exp_name: "randar_nlcd_8_tokenized"
max_iters: 100000  # More iterations for real data
global_batch_size: 128
ema: False
ema_decay: 0.9999

num_workers: 4
log_every: 50
ckpt_every: 2000
visualize_every: 50
keep_last_k: 2
resume_from: "results/randar_nlcd_8_tokenized/checkpoints/iter_22000"
global_seed: 42

results_dir: "results/" 
gpt_ckpt: None

# for eval fid:
vq_ckpt: None  # Not needed

# for wandb
wandb_entity: "ckrapu"
wandb_offline: False  # Run offline for testing 